### ISSUE TITLE
promoted input files are not design-order

### ISSUE THREAD

**Issue by spdomin** [marchdf/wallHump#2]
I noticed that your promoted input files are probably not design-order. Let's chat about this at our next stand-up if you are interested.

However, this may simply be a WIP and you are still working on dialing in the proper numerical/source settings for design-order.

**Comment by marchdf** [comment]
@spdomin yep, the files here are not for high-order (the file `mesh_promotion.i` is just so I can generate a high-order mesh, it is not used in my runs). The nalu input file I am trying out for high-order is not up here yet. Still working out some kinks. I will let you know when I push the high-order input file I want to use so you can have a look. Thanks for your help!

**Comment by spdomin** [comment]
Great... Closing:)
